### ISSUE TITLE
Formatting code fences

### ISSUE THREAD

**Issue by skaterdav85** [gcollazo/ember-cli-showdown#12]
Is there a way to format code fences in the markdown? I have a code fence in my markdown using the triple ticks followed by "js" but the code fence comes out all on one line.

**Comment by cravindra** [comment]
+1

**Comment by jasonmit** [comment]
https://github.com/gcollazo/ember-cli-showdown/commit/f2489ae4920a978965ddc2af33d9a69fb9c93e79

Feel free to reopen if you're having issues, but a test validates this isn't happening.  Perhaps you were expecting break tags insert?  That's not the default behavior, but you can achieve this with an extension.

```js
showdown.extension("newline", function() {
  return [{
    type: "output",
    regex: /\n/g,
    replace() {
      return "\n";
    }
  }];
});
```
