### ISSUE TITLE
Showdown icon extension

### ISSUE THREAD

**Issue by kgish** [gcollazo/ember-cli-showdown#13]
I'm a very happy user of the ember-cli showdown add-on and would like to create a post-processing filter that scans and replaces certain tokens using a function call.

For example, replacing all occurrences of `[:fa-icon('book'):]` via a call to `fa-icon('book')` to insert a `fontawesome` book icon.

```
function fa-icon(name) {
    return '<i class="fa fa-'+name+'"></i>';
}
```
This could be generalized to allow any function `[:fn(params):]` for most anything.

How would you recommend going about doing something like this.

**Comment by gcollazo** [comment]
You can use extensions for that. Maybe @nikz can point you in the right direction.

**Comment by nikz** [comment]
@kgish Check out https://github.com/dbtek/showdown-icon, plus the "extensions" option and you're pretty much good to go. Let me know if you need any more :smile:

**Comment by kgish** [comment]
Now that's really cool, thanks!

-- 
Kiffin Gish
Gouda, The Netherlands
