### ISSUE TITLE
Running tests on Travis results in "Cannot find module 'broccoli-funnel'"

### ISSUE THREAD

**Issue by oscarni** [gcollazo/ember-cli-showdown#21]
Since `2.7.0` tests work fine locally, but Travis fails. I'm using ember-try to test release, beta and canary versions. All versions fail and travis sais `Error: Cannot find module 'broccoli-funnel'`.

Could it be that `broccoli-funnel` needs to be specified under `dependencies` instead of `devDependencies`?

**Comment by jasonmit** [comment]
That us the issue, will fix today.

**Comment by jasonmit** [comment]
Will be versioned as part of 2.7.1
