### ISSUE TITLE
Deprecation warning in latest ember-cli

### ISSUE THREAD

**Issue by thomblake** [gcollazo/ember-cli-showdown#23]
ember-cli-showdown uses ember-cli-htmlbars@0.7.10 which is pretty outdated - latest is ember-cli-htmlbars@1.0.8

This results in a deprecation error on the command line:

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/tblake/git/web-ui/node_modules/ember-cli/lib/models/addon.js:896:27)
```

This has been fixed in newer versions of ember-cli-htmlbars

**Comment by gcollazo** [comment]
@jasonmit done!

**Comment by thomblake** [comment]
w00t! You're awesome
