### ISSUE TITLE
Will this plug-in does not support snippet grammar? 

### ISSUE THREAD

**Issue by ubuntuvim** [gcollazo/ember-cli-showdown#29]
Will this plug-in does not support snippet grammar? Not automatically formatting code segment.  
Here is my screenshot

![Here is my screenshot](http://7xnrhh.com1.z0.glb.clouddn.com/QQ20160830-0@2x.png)

On the left is the code snippet, the right style is displayed.

**Comment by gcollazo** [comment]
I think the problem is with your CSS styles. The addon produces a `<code>` tag with your example.

**Comment by ubuntuvim** [comment]
Oh,yes.i negligence. thank you for the correction.
