### ISSUE TITLE
Internal links via markdown

### ISSUE THREAD

**Issue by Crabar** [gcollazo/ember-cli-showdown#31]
I have a next problem. I have a bunch of items with descriptions. Descriptions have markdown support now (with this addon). I tried to make internal links from one item to another. It works but it reloads the whole site. When I have created the same link with `{{link-to}}` helper in html it looks the same but works in another way. It just re-render the part of app.

Is there a way to achieve `{{link-to}}` behaviour with ember-cli-showdown?

**Comment by Crabar** [comment]
I have installed addon ```ember-href-to``` and created the next extension:

```
export function initialize(/* application */) {
  showdown.extension("internal-links", function() {
  return [{
    type: 'html',
    regex: '<a href=',
    replace: '<a class="ember-href-to" href='
  }];
});
}

export default {
  name: 'register-showdown-extensions',
  initialize
};
```

This totally resolves my problem.

**Comment by Redsandro** [comment]
I prefer not to use the addon mentioned by @Crabar because it breaks a lot of things in my app, such as unrelated links.

I have exactly the same wish though. Did you find a more modern (ember 3) alternative to this, @Crabar?

Could this issue be re-opened?

**Comment by sheriffderek** [comment]
Maybe this could stay open as a feature request @Crabar ? 

Maybe someone will have time to add an option / if it gets visibility. I wanted to write my blog with Ember / so that I could have built-in Ember examples - but this has been one of the things that make me stick with other options.

**Comment by yaxinr** [comment]
I write component
my link in markdown must be "@model-name:model-id".
example
`@user:alice
`
this replaced by `{{link-to}}`
then compile by handlebars

in ember-cli-build.js
`  app.import('vendor/ember/ember-template-compiler.js')
`

md-text.coffee
```
import Ember from 'ember'
import Component from '@ember/component'
import { computed, observer } from '@ember/object'
import { htmlSafe } from '@ember/string'
import { scheduleOnce } from '@ember/runloop'
import { warn } from '@ember/debug'
import showdown from 'showdown'
import config from 'ember-get-config'

export default Component.extend(
  tagName: ''

  text: ''

  didInsertElement: ->
    scheduleOnce 'afterRender', @, 'updateTemplate'

  parsedMarkdownUnsafe: computed 'text', 'html', 'typographer', 'linkify', 'linkTarget', ->
    text = @get 'text'
    converter = new showdown.Converter config.showdown
    converter.makeHtml text

  updateTemplate: ->
    @set('subLayout', null)
    dynamic = @get 'dynamic'
    self = @
    scheduleOnce 'afterRender', @, ->
      try
        layout = null
        re = /[@]([a-z-]+):(\S+)/g
        replaced = self.get 'parsedMarkdownUnsafe'
        .replace(re, "{{#link-to '$1.item' '$2'}}$2{{/link-to}}")
        replaced = htmlSafe replaced if !dynamic
        layout = Ember.Handlebars.compile replaced, false
        self.set 'subLayout', layout
      catch e
        console.log e
  observerSource: observer 'text', ->
    @updateTemplate()
).reopenClass
  positionalParams: ['text']

```
md-text.emblem
```
if subLayout
  = md-text-renderer layout=subLayout
```
md-text-renderer.coffee
```
import Component from '@ember/component'

export default Component.extend
  tagName: ''
```

using
`md-text '# 123'`
