### ISSUE TITLE
Showdown crashes if a safe string is passed as an argument

### ISSUE THREAD

**Issue by lolmaus** [gcollazo/ember-cli-showdown#34]
I'm trying to use `ember-cli-showdown` together with `ember-i18n`. `ember-i18n` wraps the resulting string in `Ember.String.htmlSafe`.

The Showdown library is not aware of Ember's safe strings so it crashes with `text.replace is not a function`.

**Comment by jasonmit** [comment]
Responded with my concerns and an alternative in the PR

**Comment by javogel** [comment]
@jasonmit, I cant find the PR to review said alternative. Im having the same issue as @lolmaus lolmaus. Could you please help by pointing me in the right direction?

**Comment by jasonmit** [comment]
@javogel https://github.com/gcollazo/ember-cli-showdown/pull/35
