### ISSUE TITLE
markdown-to-html insert <br/> for newlines

### ISSUE THREAD

**Issue by kgish** [gcollazo/ember-cli-showdown#4]
I was just wondering if it's possible to configure `markdown-to-html` so that it will replace all newlines `'\n'` for `'<br />'` tags.

**Comment by gcollazo** [comment]
It does add a <br> tag. Added a simple test to demo it.

https://github.com/gcollazo/ember-cli-showdown/blob/master/tests/unit/components/markdown-to-html-test.js#L41-L53

**Comment by kgish** [comment]
Strange, I must be doing something wrong. Maybe I need to re-install the latest version.

**Comment by gcollazo** [comment]
Just make sure you have 2 spaces before the `\n` according to [the spec](http://spec.commonmark.org/0.18/#hard-line-breaks).
