### ISSUE TITLE
Upgrade for compatibility with Ember-CLI 2.13

### ISSUE THREAD

**Issue by vmalloc** [gcollazo/ember-cli-showdown#44]
Currently ember-cli-showdown uses ember-cli-htmlbars-inline-precompile 0.3.8, which does not support Babel 6. This causes projects using this addon and wanting to upgrade to ember-cli 2.13 to break

**Comment by jasonmit** [comment]
Published as 3.1.0

**Comment by vmalloc** [comment]
@jasonmit thanks!
