### ISSUE TITLE
Must ember-cli-htmlbars-inline-precompile be a dependency?

### ISSUE THREAD

**Issue by lukemelia** [gcollazo/ember-cli-showdown#46]
Because ember-cli-htmlbars-inline-precompile is a dependency of ember-cli-showndown (as opposed to a devDependency), it forces any app depending on ember-cli-showdown  to use babel 6. Is this intended? Is it avoidable?

**Comment by jasonmit** [comment]
It is needed but avoidable by moving it's own template and dropping inline-precompile.

https://github.com/gcollazo/ember-cli-showdown/blob/master/addon/components/markdown-to-html.js#L17

I will address within the hour and release a patch release.

**Comment by jasonmit** [comment]
@lukemelia should be resolved as part of 3.1.1

**Comment by lukemelia** [comment]
Thanks for the rapid response @jasonmit!

**Comment by chrislopresto** [comment]
Nice!
