### ISSUE TITLE
Ability to inline MD files

### ISSUE THREAD

**Issue by jasonmit** [gcollazo/ember-cli-showdown#54]
`{{markdown-to-html path="README.md"}}`

```
var app = new EmberAddon({
  showdownPaths: ['public/markdown']
});
```

Reference: https://github.com/ef4/ember-code-snippet#usage

**Comment by MelSumner** [comment]
+1 to this issue. I am also trying to use the README file in the dummy app for my Ember addon. I wonder if @mansona has dealt with this idea in Empress?
