### ISSUE TITLE
showdown-highlight

### ISSUE THREAD

**Issue by rwwagner90** [gcollazo/ember-cli-showdown#62]
Hi, thanks for the addon!

I see I can write my own extensions, but how can I use this one? https://github.com/Bloggify/showdown-highlight

**Comment by jasonmit** [comment]
So long as you're import/bundle the extension within your app, it would look something like below.  This plugin exports a function, which is the extension function.
https://github.com/Bloggify/showdown-highlight/blob/master/lib/index.js#L8

```js
import showdownHightlight from 'showdown-highlight'; 
import showdown from 'showdown';

/**
  * Somewhere in your app code before the component is rendered.
  * perhaps an initializer or route hook?
  */

showdown.extension("showdownHighlight", showdownHightlight);
```

```hbs
{{markdown-to-html
  markdown=postContent
  extensions='showdownHighlight'}}
```

**Comment by rwwagner90** [comment]
@jasonmit I've been trying all day to get this working. All the various ember rollup solutions do not work, and there seems to be no way to do this. If you know of a way that works, that would be great!

**Comment by jasonmit** [comment]
@rwwagner90 okay I have an idea that I'll kick the tires on.  I'll publish an addon called `ember-showdown-highlight` and make you the co-owner if you want to carry the torch forward afterwards.

**Comment by rwwagner90** [comment]
@jasonmit I already published an addon to try to do it with https://github.com/shipshapecode/ember-showdown-highlight I just added you as a collaborator.

**Comment by aalimovs** [comment]
Anyone else stumbling on this, @rwwagner90's addon works great along with the @jasonmit's initializer above.

Just don't forget to add the `highlight.js`'s css.
