### ISSUE TITLE
global ENV options don't work for engines

### ISSUE THREAD

**Issue by mattmarcum** [gcollazo/ember-cli-showdown#63]
When you use showdown inside an engine the global options from the parent app aren't being read out of the config.  I think using `ember-get-config` would fix this problem.  The `markdown-to-html` component just looks up the config for the engine addon, not the parent.

**Comment by jasonmit** [comment]
@mattmarcum PRs are welcome, I know nothing about engines in order to support this.

**Comment by jasonmit** [comment]
@mattmarcum can you verify that https://github.com/gcollazo/ember-cli-showdown/pull/64 resolves your issue

**Comment by jasonmit** [comment]
https://github.com/ember-engines/ember-engines/issues/176 this is an upstream issue and it's unsolved for now.
