### ISSUE TITLE
Markdown helper for outlet

### ISSUE THREAD

**Issue by jchamet** [gcollazo/ember-cli-showdown#7]
I want to create templates that are markdown-only and render them into an outlet that converts the outlet content to standard html. I think this would be an important feature since people typically use markdown for large blocks of text and not single lines, and this would allow people to easily create pages in markdown without haven't to mess with properties every time.

**Comment by gcollazo** [comment]
Thanks for the idea but I prefer to pass the raw text as an `attr` to the component. Feels like a more conventional way of doing things in ember. Also have in mind that your can pass as much source markdown as you want, is not limited to a single line.
