### ISSUE TITLE
How to call makeHtml in component js action method

### ISSUE THREAD

**Issue by SantoshRaoBlr** [gcollazo/ember-cli-showdown#71]
After doing an import of showdown, import showdown from 'showdown';
 I can call methods like showdown.setOption('literalMidWordUnderscores',true)

But is there a way I can convert markup to html, something like this in component js action method

showdown.Converter.makeHtml(fileContents)

**Comment by yaxinr** [comment]
```
    converter = new showdown.Converter(config.showdown)
    converter.makeHtml text

```

**Comment by SantoshRaoBlr** [comment]
Thank you, will try
