### ISSUE TITLE
Ember 3.9 Deprecation in extensions property

### ISSUE THREAD

**Issue by Unkrass** [gcollazo/ember-cli-showdown#74]
With Ember 3.9 I get the following deprecation warning:

DEPRECATION: The <eos@component:markdown-to-html::ember874>#extensions computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.

I believe that it would be enough to remove the computed property, since it simply returns an empty array.

ember-cli-showdown/addon/components/markdown-to-html.js, line 15:
`extensions: computed(function() {
    return [];
  }),`

**Comment by shijiezhou1** [comment]
Please fixed the extension and it is not working @gcollazo

**Comment by bench-marc** [comment]
https://github.com/gcollazo/ember-cli-showdown/pull/82

**Comment by Unkrass** [comment]
@gcollazo @jasonmit can you merge bench-marc's PR any time soon?

**Comment by jasonmit** [comment]
@Unkrass should be fixed in 4.5.0

**Comment by Unkrass** [comment]
@jasonmit much appreciated
