### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by kedano** [gcollazo/ember-cli-showdown#8]
I get the following error when I try to use the plugin in a ember-cli 1.13.6 project with a pod structure:

```
Error: Could not find module `ember-cli-showdown/components/markdown-to-html` imported from `designguidlines/components/markdown-to-html`
```

"designguidelines" is just my folder/project name.

The same setup works just fine when I use ember-cli 1.13.1.

**Comment by jasonmit** [comment]
This is unlikely due to anything related to this library.
